In [1]:
import pandas as pd
from sqlalchemy import create_engine
import plotly.express as px
import seaborn as sns

In [2]:
engine = create_engine(
    "postgresql+psycopg2://andrevsilva:andrevsilva@localhost:5432/datasql"
)

customers = pd.read_sql("SELECT * FROM customers", engine)
products = pd.read_sql("SELECT * FROM products", engine)
orders = pd.read_sql("SELECT * FROM orders", engine)

In [3]:
customers.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'phone',
       'birth_date', 'gender', 'street', 'city', 'state', 'country', 'zipcode',
       'signup_date', 'customer_segment', 'loyalty_points', 'marketing_optin',
       'last_login'],
      dtype='str')

In [4]:
customers.head()

,customer_id,first_name,last_name,email,phone,birth_date,gender,street,city,state,country,zipcode,signup_date,customer_segment,loyalty_points,marketing_optin,last_login
0,ec4158d4-59ef-4d3e-a80c-45753e723951,Katherine,Adams,johnsonjohn@example.org,2332023333,2005-02-01,Female,938 Smith Brook Suite 934,Wilsonton,Maine,Serbia,08811,2023-07-10,VIP,2937,False,2023-07-24 06:47:02.342840
1,2273168a-0546-4adc-ae93-e3e430518bc4,Mario,Baker,keithpeterson@example.com,547.744.9956,1999-01-15,Female,063 Craig Parks,Garyland,Alabama,Nigeria,20603,2024-06-20,Gold,1363,True,2025-10-21 04:10:59.885276
2,a3199887-fcc1-4de7-bcc0-bedda7bbecf5,Stephanie,Watkins,danielle57@example.org,370.310.8591x245,1947-10-15,Female,232 Jeffrey Highway Apt. 308,Lake Angelaview,Delaware,Germany,67975,2023-11-01,Basic,161,False,2024-11-16 12:40:40.372940
3,6384d98f-530b-48fd-8631-eb392ff72fd2,Tammy,Johnson,lopezwilliam@example.org,+1-713-570-5017x1852,1985-01-27,Female,05045 Hoffman Walk,Hernandeztown,Hawaii,Norway,95292,2025-10-25,Basic,3075,False,2025-12-09 09:23:27.496656
4,531e5a18-3a26-4bb3-876e-8b3619a0b5d6,James,Morris,joydiaz@example.net,+1-888-968-3668x518,1981-12-07,Male,0965 Timothy Burg,Rivasshire,Pennsylvania,Ethiopia,82047,2024-12-31,Silver,2652,True,2025-09-15 22:31:51.848695

In [5]:
customers.dtypes

customer_id                    str
first_name                     str
last_name                      str
email                          str
phone                          str
birth_date                  object
gender                         str
street                         str
city                           str
state                          str
country                        str
zipcode                        str
signup_date                 object
customer_segment               str
loyalty_points               int64
marketing_optin               bool
last_login          datetime64[us]
dtype: object

In [6]:
# Convert to datetime
customers["birth_date"] = pd.to_datetime(customers["birth_date"])

In [7]:
customers.dtypes

customer_id                    str
first_name                     str
last_name                      str
email                          str
phone                          str
birth_date           datetime64[s]
gender                         str
street                         str
city                           str
state                          str
country                        str
zipcode                        str
signup_date                 object
customer_segment               str
loyalty_points               int64
marketing_optin               bool
last_login          datetime64[us]
dtype: object

In [16]:
customers.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'phone',
       'birth_date', 'gender', 'street', 'city', 'state', 'country', 'zipcode',
       'signup_date', 'customer_segment', 'loyalty_points', 'marketing_optin',
       'last_login', 'age'],
      dtype='str')

In [8]:
today = pd.Timestamp.today()
customers["age"] = (today - customers["birth_date"]).dt.days // 365

In [9]:
customers.head()

,customer_id,first_name,last_name,email,phone,birth_date,gender,street,city,state,country,zipcode,signup_date,customer_segment,loyalty_points,marketing_optin,last_login,age
0,ec4158d4-59ef-4d3e-a80c-45753e723951,Katherine,Adams,johnsonjohn@example.org,2332023333,2005-02-01,Female,938 Smith Brook Suite 934,Wilsonton,Maine,Serbia,08811,2023-07-10,VIP,2937,False,2023-07-24 06:47:02.342840,21
1,2273168a-0546-4adc-ae93-e3e430518bc4,Mario,Baker,keithpeterson@example.com,547.744.9956,1999-01-15,Female,063 Craig Parks,Garyland,Alabama,Nigeria,20603,2024-06-20,Gold,1363,True,2025-10-21 04:10:59.885276,27
2,a3199887-fcc1-4de7-bcc0-bedda7bbecf5,Stephanie,Watkins,danielle57@example.org,370.310.8591x245,1947-10-15,Female,232 Jeffrey Highway Apt. 308,Lake Angelaview,Delaware,Germany,67975,2023-11-01,Basic,161,False,2024-11-16 12:40:40.372940,78
3,6384d98f-530b-48fd-8631-eb392ff72fd2,Tammy,Johnson,lopezwilliam@example.org,+1-713-570-5017x1852,1985-01-27,Female,05045 Hoffman Walk,Hernandeztown,Hawaii,Norway,95292,2025-10-25,Basic,3075,False,2025-12-09 09:23:27.496656,41
4,531e5a18-3a26-4bb3-876e-8b3619a0b5d6,James,Morris,joydiaz@example.net,+1-888-968-3668x518,1981-12-07,Male,0965 Timothy Burg,Rivasshire,Pennsylvania,Ethiopia,82047,2024-12-31,Silver,2652,True,2025-09-15 22:31:51.848695,44

In [10]:
fig = px.histogram(
    customers,
    x="age",
    nbins=20,
    title="Age Distribution"
)

fig.show()

In [15]:
fig = px.histogram(
    customers,
    x="age",
    color="gender",
    nbins=20,
    barmode="overlay",
    title="Age Distribution by Gender"
)

fig.show()

In [11]:
products.columns

Index(['product_id', 'product_name', 'category', 'brand', 'price', 'cost',
       'weight_kg', 'color', 'release_date', 'warranty_months', 'rating',
       'reviews_count', 'stock_quantity', 'supplier', 'origin_country',
       'is_active'],
      dtype='str')

In [12]:
products.head()

,product_id,product_name,category,brand,price,cost,weight_kg,color,release_date,warranty_months,rating,reviews_count,stock_quantity,supplier,origin_country,is_active
0,1,Color,Accessories,Flowers-Schmidt,2718.15,1265.85,3.80,FireBrick,2023-01-05,12,3.6,1943,826,Tran-Davis,Moldova,True
1,2,Financial,Office,Savage and Sons,2808.99,1144.18,0.41,PaleGreen,2024-11-23,6,2.7,2918,98,Keith LLC,Algeria,True
2,3,Land,Gaming,Casey Inc,4738.22,2379.54,3.68,LightBlue,2025-04-01,24,2.7,3298,485,Franklin-Freeman,Iceland,True
3,4,Manager,Office,Cook-Walker,3974.31,2439.86,0.13,GreenYellow,2022-05-30,24,4.5,1317,375,Short Inc,Guernsey,True
4,5,Entire,Office,Harris-Sanchez,3778.57,1911.33,3.53,DarkGoldenRod,2023-09-27,6,3.6,4681,484,Rowland-Campos,Kenya,True

In [13]:
orders.columns

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'unit_price',
       'discount_percent', 'total_amount', 'order_date', 'payment_method',
       'payment_status', 'shipping_method', 'shipping_cost', 'order_status',
       'delivery_days', 'warehouse', 'sales_channel', 'coupon_used',
       'customer_rating'],
      dtype='str')

In [14]:
orders.head()

,order_id,customer_id,product_id,quantity,unit_price,discount_percent,total_amount,order_date,payment_method,payment_status,shipping_method,shipping_cost,order_status,delivery_days,warehouse,sales_channel,coupon_used,customer_rating
0,1,73926628-0b75-4a86-a648-4c9fc213ab23,22,1,69.68,0,69.68,2025-10-09,credit_card,paid,pickup,19.37,processing,6,SP01,mobile_app,True,NaN
1,2,36283371-a0d5-46ff-813a-31cc5fdafdd7,34,5,2808.99,5,13342.70,2025-08-09,debit_card,refunded,pickup,8.40,processing,9,MG01,marketplace,True,NaN
2,3,e20888b8-dc6f-4556-b299-4ee7b7b87af5,6,2,3962.61,0,7925.22,2025-03-12,pix,paid,express,27.00,cancelled,3,SP02,mobile_app,True,2.0
3,4,3a29271a-d1a0-466f-b6f7-dd46265aac0b,7,4,3830.33,0,15321.32,2025-04-23,paypal,paid,pickup,47.18,processing,8,SP01,marketplace,True,NaN
4,5,2babe608-960f-4f25-8c04-1bd2211e954a,27,5,3778.57,0,18892.85,2026-01-22,pix,refunded,express,29.42,cancelled,3,MG01,mobile_app,False,3.0